### ISSUE TITLE
option for primitive equality check

### ISSUE THREAD

**Issue by godspeedyou** [GuavaEclipsePlugin/GuavaEclipsePluginParent#25]
Your plugin would be perfect, if it could automatically detect if a field was primitive and if it'd use the "==" operator to check equality instead of Objects.equal(Object, Object), so unnecessary type casting would be avoided.

**Comment by arolfes** [comment]
it is not that easy to detect if a field is primitive with the eclipse internal resource classes.
i will investigate it

**Comment by arolfes** [comment]
feature is implemented and as snapshot available under https://sourceforge.net/projects/guavaeclipse/files/SNAPSHOTS/UpdateSite/LATEST/

for a full release a i will add some more integration tests
