### ISSUE TITLE
Make release jar available on Github

### ISSUE THREAD

**Issue by tomasbjerre** [GuavaEclipsePlugin/GuavaEclipsePluginParent#28]
Would be nice if I could get it from:
https://github.com/GuavaEclipsePlugin/GuavaEclipsePluginParent/releases

**Comment by arolfes** [comment]
it is not that easy

i will upload manually the update site

do you want the plugins.jar seperatly ?

**Comment by arolfes** [comment]
i will manually upload the updatesite to releases
