### ISSUE TITLE
Escape autoboxing for primitive types 

### ISSUE THREAD

**Issue by foal** [GuavaEclipsePlugin/GuavaEclipsePluginParent#30]
e.g generated `hashCode` now

``` Java
    public int hashCode() {
        return Objects.hashCode(super.hashCode(), getOffset());
    }
```

have to be

``` Java
    public int hashCode() {
        return Objects.hashCode(Integer.valueOf(super.hashCode()), Long.valueOf(getOffset()));
    }
```

the same for `equals`

**Comment by arolfes** [comment]
Hi foal,

can you check the new version.
There is a setting called "for primitives don't use Objects method to avoid casting" https://guavaeclipseplugin.github.io/images/GuavaEclipsePlugin_Preferences_EqualsHashCode.png

i will add some documentation about this setting

can you check if this behavior fits your needs?
If yes, please let me know
if not let us talk about an example.

**Comment by arolfes** [comment]
I think i get your point

you want an option to enable explicite AutoBoxing.

**Comment by foal** [comment]
Yes, I see it as following options:
( ) generate it as it
( ) add @SuppressWarnings("boxing") annotation
( ) use the explicit boxing

I check the current version - it solves the issue for equals method, but we still have autoboxing in a hash.

**Comment by arolfes** [comment]
hi foal,

can you test current snapshot, please.
update site is here: [https://dl.bintray.com/guavaeclipseplugin/GuavaEclipsePlugin/SNAPSHOT/latest/](https://dl.bintray.com/guavaeclipseplugin/GuavaEclipsePlugin/SNAPSHOT/latest/)

Window -> Preferences -> Guava Preferences -> Equals/HashCode Methods Preferences
there is a new RadioGroup "autoboxing, supressWarning(boxing), explicit boxing for primitives"

One thing to know for equals methods: the selection of the new radio group has no effect so long the checkbox "For primitives don't use Objects method in equals() to avoid casting" is selected.
