### ISSUE TITLE
Error installing from Eclipse Market Place

### ISSUE THREAD

**Issue by godspeedyou** [GuavaEclipsePlugin/GuavaEclipsePluginParent#36]
When installing from within Eclipse Neon's Market Place I get the following error message after accepting the download.

An error occurred while collecting items to be installed
session context was:(profile=_eclipse_neon_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at https://sourceforge.net/projects/guavaeclipse/files/UpdateSite/LATEST/features/GuavaEclipseFeature_1.4.0.jar.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by ghost** [comment]
+1

**Comment by bmarwell** [comment]
:+1: 

Actually, you probably just have to add [Geotrusts root certificate](https://www.geotrust.com/resources/root-certificates/index.html) to your truststore.
You can use a tool like [keystore explorer](http://keystore-explorer.org/) to add them.

This is nothing the author can do about, besides moving the eclipse repository to github pages.

**Comment by vguna** [comment]
Sourceforge should just provide a well known SSL cert. Instead of forcing users to add some unknown certs... just my two cents. Also stumbled across this :(...

**Comment by arolfes** [comment]
i hoped the guys from sourceforge would provide a propper SSL cert
i start working on a solution with eclipse updatesite and github releases (https://developer.github.com/v3/repos/releases/#upload-a-release-asset)

**Comment by arolfes** [comment]
as the release asset mechanism from github does not work for EclipsePluginUpdateSites i found this article https://blog.bintray.com/2014/03/11/hosting-your-eclipse-update-site-p2-on-bintray-com/

i moved the 1.4.0 release to bintray 
new update site https://dl.bintray.com/guavaeclipseplugin/GuavaEclipsePlugin/1.4.0/

i hope bintray provides for longer time a "well known" ssl cert.

**Comment by arolfes** [comment]
https://dl.bintray.com/guavaeclipseplugin/GuavaEclipsePlugin/latest/

**Comment by arolfes** [comment]
for snapshot releases
https://dl.bintray.com/guavaeclipseplugin/GuavaEclipsePlugin/SNAPSHOT/latest/
